 #Êı¾İ¿âÅäÖÃ
  spring:
    datasource:
      username: lq
      password: 19990418
      url: jdbc:mysql://47.94.107.225:3306/chatnt?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        max-lifetime: 1800000
        #ÓÊ¼şÅäÖÃ
    mail:
      protocol: smtp
      default-encoding: UTF-8
      host: smtp.163.com
      password: q19990418
      test-connection: true
      username: chatnt@163.com
 #mybatisplusÅäÖÃ
  mybatis-plus:
    mapper-locations: classpath*:mapper/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: false
#ÓÊ¼şÅäÖÃ
