
  spring:
    datasource:
      username: lq
      password: 19990418
      url: jdbc:mysql://47.94.107.225:3306/chatnt?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        max-lifetime: 30000
        connection-test-query: SELECT 1

    mail:
      protocol: smtp
      default-encoding: UTF-8
      host: smtp.163.com
      password: q19990418
      test-connection: true
      username: chatnt@163.com
      properties:
        mail:
          smtp:
            starttls:
              enable: true
              required: true
            auth: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
              port: 465




  mybatis-plus:
    mapper-locations: classpath*:mapper/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: false

    type-aliases-package: club.chatnt.entity
  server:
    port: 8080
